#ifndef UTOTPARSER_UTILS_H
#define UTOTPARSER_UTILS_H

#include <sstream>
#include <unordered_map>
#include "nlohmann/json.hpp"

#include "Exceptions.h"
#include "XMLtoJSONInclude/xml2json.hpp"
#include "defines/UPPAALxmlAttributes.h"
#include "defines/TOjsonAttributes.h"

using json = nlohmann::json;


/**
 * Function used to return a json representation starting from a file. Notice that the file must be an .xml file.
 * @param file the file from which to get a json representation.
 * @return a json representation of the given file.
 */
json getJsonFromFileStream(std::ifstream &file, bool isXml = true)
{
    if (isXml)
    {
        std::stringstream buffer;
        buffer << file.rdbuf();
        file.close();

        std::string tmp = buffer.str();
        const char *xml_str = tmp.c_str();

        // We obtain the json representation of a TA from the xml generated by UPPAAL.
        return json::parse(xml2json(xml_str));
    } else
        throw NotXMLFormatException("Provided file should be of .xml type!");
}


/**
 * Function used to form bounds part in .xml json
 * @param TOfile json representation of the .tot file
 * @param result the result json
 */
void formJsonBounds(const json &TOfile, json &result)
{
    std::string bound_declaration_string;
    int bound_idx = 0;

    for (const auto &bound : TOfile[TOBOUNDS])
    {
        if (bound_idx != 0)
            bound_declaration_string += "|";

        json left = bound[TOLEFT], right = bound[TORIGHT];

        bound_declaration_string += "bound";
        if (left.is_number())
        {
            bound_declaration_string += ":";
            bound_declaration_string += std::to_string(left.get<int>());
        }
        else if (left.is_string())
        {
            bound_declaration_string += ":";
            bound_declaration_string += left.get<std::string>();
        }

        if (right.is_number())
        {
            bound_declaration_string += ":";
            bound_declaration_string += std::to_string(right.get<int>());
        }
        else if (right.is_string())
        {
            bound_declaration_string += ":";
            bound_declaration_string += right.get<std::string>();
        }

        bound_idx++;
    }

    result[NTA][DECLARATION] = bound_declaration_string;
}


/**
 * Function used to form clocks part in .xml json
 * @param TOfile json representation of the .tot file
 * @param result the result json
 */
void formJsonClocks(const json &TOfile, json &result)
{
    std::string clock_declaration_string;
    int clock_idx = 0;
    clock_declaration_string += "// Place local declarations here.\nclock ";

    for (const auto &clock : TOfile[TOCLOCKS])
    {
        clock_declaration_string += (clock_idx != 0) ? ", " : "";
        clock_declaration_string += clock[TONAME].get<std::string>();
        clock_idx++;
    }

    clock_declaration_string += ";";
    result[NTA][TEMPLATE][DECLARATION] = clock_declaration_string;
}


/**
 * Function used to form locations part in .xml json
 * @param TOfile json representation of the .tot file
 * @param result the result json
 * @param state_id_to_name mapping from state id to state name
 */
void formJsonLocations(const json &TOfile, json &result, std::unordered_map<int, std::string> &state_id_to_name)
{
    json &locations = result[NTA][TEMPLATE][LOCATION];
    locations = json::array();
    int states_num = TOfile[TONSTATES].get<int>();
    json inputs = TOfile[TOINPUT], outputs = TOfile[TOOUTPUT], acceptings = TOfile[TOACCEPTING];
    int input_comments_num = TOfile[TONINPUTCOMMENTS].get<int>();
    json input_comments = TOfile[TOINPUTCOMMENTS];

    for (int i = 0; i < states_num; i++)
    {
        json location;
        std::string state_name = "id" + std::to_string(i);
        location[ID] = state_name;
        state_id_to_name.emplace(i, state_name);

        // form input symbol for input location
        for (const auto &input : inputs)
        {
            if (input.get<int>() == i)
            {
                location[NAME][TEXT] = "in";
                break;
            }
        }

        // form output symbol for output location
        for (const auto &output : outputs)
        {
            if (output.get<int>() == i)
            {
                location[NAME][TEXT] = "out";
                break;
            }
        }

        // form accpeting location symbol
        for (const auto &accepting:acceptings)
        {
            if (accepting.get<int>() == i)
            {
                location[COLOR] = "SYMBOL";
                break;
            }
        }

        for (int j = 0; j < input_comments_num; j++)
        {
            if (i == input_comments[j][TOID].get<int>())
            {
                std::string input_comment_string = input_comments[j][TOACTION][TOCLOCK].get<std::string>() + " = " +
                                                   std::to_string(input_comments[j][TOACTION][TOVALUE].get<int>());
                location[LABEL][TEXT] = input_comment_string;
                location[LABEL][KIND] = "comments";
            }
        }

        locations.push_back(location);
    }
}


/**
 * Function used to form transitions part in .xml json
 * @param TOfile json representation of the .tot file
 * @param result the result json
 * @param state_id_to_name mapping from state id to state name
 */
void formJsonTransitions(const json &TOfile, json &result, const std::unordered_map<int, std::string> &state_id_to_name)
{
    json &transitions = result[NTA][TEMPLATE][TRANSITION];
    transitions = json::array();
    int transitions_num = TOfile[TONTRANSITIONS].get<int>();
    int transition_idx = state_id_to_name.size();

    if (TOfile[TONTRANSITIONS].get<int>() != 0)
    {
        for (const auto &transition : TOfile[TOTRANSITIONS])
        {
            json jtransition;

            jtransition[ID] = "id" + std::to_string(transition_idx);
            jtransition[SOURCE][REF] = state_id_to_name.at(transition[TOFROM].get<int>());
            jtransition[TARGET][REF] = state_id_to_name.at(transition[TOTO].get<int>());

            if (transition[TONGUARDS].get<int>() != 0 or transition[TONACTIONS].get<int>() != 0)
                jtransition[LABEL] = json::array();

            if (transition[TONGUARDS].get<int>() != 0)
            {
                std::string guards_string;
                int guard_idx = 0;

                for (const auto &guard : transition[TOGUARDS])
                {
                    if (guard_idx != 0)
                        guards_string += " && ";

                    guards_string += guard[TOCLOCK].get<std::string>();
                    guards_string += " ";
                    guards_string += guard[TOOP].get<std::string>();
                    guards_string += " ";
                    guards_string += (guard[TOVALUE].is_number()) ? std::to_string(guard[TOVALUE].get<int>())
                                                                  : guard[TOVALUE].get<std::string>();
                    guard_idx++;
                }

                json jguards;
                jguards[TEXT] = guards_string;
                jguards[KIND] = "guard";
                jtransition[LABEL].push_back(jguards);
            }

            if (transition[TONACTIONS].get<int>() != 0)
            {
                std::string actions_string;
                int action_idx = 0;

                for (const auto &action : transition[TOACTIONS])
                {
                    if (action_idx != 0)
                        actions_string += " && ";

                    actions_string += action[TOCLOCK].get<std::string>();
                    actions_string += " = ";
                    actions_string += (action[TOVALUE].is_number()) ? std::to_string(action[TOVALUE].get<int>())
                                                                    : action[TOVALUE].get<std::string>();
                    action_idx++;
                }

                json jactions;
                jactions[TEXT] = actions_string;
                jactions[KIND] = "assignment";
                jtransition[LABEL].push_back(jactions);
            }

            transitions.push_back(jtransition);
        }
    }
}


/**
 * Function used to form other parts not handled yet in .xml json
 * @param TOfile json representation of the .tot file
 * @param result the result json
 * @param state_id_to_name mapping from state id to state name
 */
void formJsonOthers(const json &TOfile, json &result, const std::unordered_map<int, std::string> &state_id_to_name)
{
    json jinitial = TOfile[TOINITIAL];

    if (!jinitial.empty())
    {
        result[NTA][TEMPLATE][INIT][REF] = state_id_to_name.at(jinitial[0].get<int>());
    }
}


/**
 * Function used to return a json representation in the system from a .tot file
 * @param file the file from which to get a json representation.
 * @return a TOT-version json representation of the given file.
 */
json getJsonFromTOFile(std::ifstream &file, bool isTot = true)
{
    if (isTot)
    {
        json j_object;
        file >> j_object;

        if (file.fail())
            std::cerr << "failed to read json from .tot file" << std::endl;

        // make a json representation from .tot file
        json result;
        std::unordered_map<int, std::string> state_id_to_name;

        // form declaration (bound)
        formJsonBounds(j_object, result);

        // form decalaration (clocks)
        formJsonClocks(j_object, result);

        // form locations (as there is no name for state(location) in .tot file, we need to generate it
        // and we stored the mapping from id to name in state_id_to_name)
        formJsonLocations(j_object, result, state_id_to_name);

        // form transitions
        formJsonTransitions(j_object, result, state_id_to_name);

        // form other parts of json
        formJsonOthers(j_object, result, state_id_to_name);

        return result;
    }
    else
        throw NotTOTFormatException("Provided file should be of .tot type!");
}


/**
 * Function used to return a json representation in the system from a .totj file
 * @param file the file from which to get a json representation.
 * @return a TOTJ-version json representation of the given file.
 */
json getJsonFromTOJFile(std::ifstream &file, bool isTotj = true)
{
    if (isTotj)
    {
        json j_object;
        file >> j_object;

        if (file.fail())
            std::cerr << "failed to read json from .tot file" << std::endl;

        return j_object;
    }
    else
        throw NotTOTJFormatException("Provided file should be of .totj type!");
}


/**
 * Function used to collect inside a vector all the integer occurrences inside a string.
 * @param str the string into which we're looking for integers occurrences.
 * @return a vector containing all integer numbers present in the string parameter.
 */
static std::vector<int> extractIntegersFromString(const std::string &str)
{
    std::vector<int> result;
    std::stringstream ss(str);
    std::string temp;

    while (ss >> temp)
    {
        try
        {
            int found = std::stoi(temp);
            result.push_back(found);
        }
        catch (const std::invalid_argument &)
        {}
        catch (const std::out_of_range &)
        {}
    }
    return result;
}


/**
 * Function that returns the maximum integer value that appears inside a string.
 * @param str the string into which we're looking for integers occurrences.
 * @return the maximum integer value appearing in the string parameter.
 */
static int getMaxIntFromStr(const std::string &str)
{
    std::vector<int> tmp = extractIntegersFromString(str);
    return (!tmp.empty()) ? *max_element(tmp.begin(), tmp.end()) : 0;
}


/**
 * Function used to delete all contents of a given directory.
 * @param dir the path to the directory to clear.
 */
void deleteDirectoryContents(const std::filesystem::path &dir)
{
    for (const auto &entry: std::filesystem::directory_iterator(dir))
        std::filesystem::remove_all(entry.path());
}


/**
 * Function that, given a string containing some symbols, returns the last word after the last occurrence of such symbol.
 * @param str the string in which we look for the last word.
 * @param symbol the token appearing in the string.
 * @return the last word following the last occurrence of symbol.
 */
std::string getWordAfterLastSymbol(const std::string &str, char symbol)
{
    size_t lastSlashPos = str.find_last_of(symbol);
    if (lastSlashPos != std::string::npos)
        return str.substr(lastSlashPos + 1);
    else
        return "";
}


/**
 * Function used to get a specific string obtained by splitting the original one.
 * @param str the string to split.
 * @param symbol the token used for splitting the string.
 * @param pos the position of the string to return. The position is considered on the result of the splitting operation.
 * @return the string at position pos in the split original string.
 */
std::string getStringGivenPosAndToken(const std::string &str, char symbol, int pos)
{
    std::istringstream stream(str);
    std::string token;
    std::vector<std::string> tokens;

    while (std::getline(stream, token, symbol))
        tokens.push_back(token);

    return tokens[pos];
}


/**
 * Function used to split a string based on a given character and then get all the tokens obtained.
 * @param str the string to split.
 * @param symbol the character that will be used to split the 'str' parameter in substrings.
 * @return a vector of strings containing substrings obtained from the original one.
 */
std::vector<std::string> getTokenizedString(const std::string &str, char symbol) {
    std::istringstream stream(str);
    std::string token;
    std::vector<std::string> tokens;

    while (std::getline(stream, token, symbol))
        tokens.push_back(token);

    return tokens;
}


/**
 * Function used to get all the entries in a directory sorted in alphabetical order.
 * @param directory_path the path to the directory in which to collect all entries.
 * @return a vector containing the alphabetically ordered entries.
 */
std::vector<std::filesystem::directory_entry> getEntriesInAlphabeticalOrder(const std::filesystem::path &directory_path)
{
    std::vector<std::filesystem::directory_entry> entries;

    // Iterate over the directory and collect the entries.
    for (const auto &entry: std::filesystem::directory_iterator(directory_path))
        entries.push_back(entry);

    // Sort the entries alphabetically.
    std::sort(entries.begin(), entries.end(), [](const auto &a, const auto &b) {
        // We have to provide sort a sorting criterion by using return sorting_criterion.
        return a.path().filename() < b.path().filename();
    });
    return entries;
}


/**
 * Function used to substitute all occurrences of a given character inside a string with another string.
 * @param originalString the string in which we want to substitute a character.
 * @param charToReplace the character to replace.
 * @param replacementString the string with which we want to replace the character.
 * @return a string in which, starting from originalString, we replaced every charToReplace with replacementString.
 */
std::string substituteCharInString(std::string originalString, char charToReplace, const std::string &replacementString)
{
    size_t pos = 0;
    while ((pos = originalString.find(charToReplace, pos)) != std::string::npos)
    {
        originalString.replace(pos, 1, replacementString);
        pos += replacementString.length();
    }
    return originalString;
}


/**
 * Method used to substitute the first occurrence of a given string inside a string with another string.
 * The input string is not modified, a result is returned containing the replaced strings.
 * @param inputStr the string in which to replace the desired string.
 * @param toReplace the string to look for in 'inputStr' and to replace.
 * @param replacement the string with which the string 'toReplace' is going to be replaced.
 * @return a string equal to 'inputStr', where the first occurrence of 'toReplace' has been substituted with 'replacement'.
 */
std::string subSinS(const std::string &inputStr, const std::string &toReplace, const std::string &replacement)
{
    std::string tmpCopy = inputStr;

    size_t pos = tmpCopy.find(toReplace);

    if (pos != std::string::npos)
        tmpCopy.replace(pos, toReplace.length(), replacement);

    return tmpCopy;
}


/**
 * Method used to insert a whitespace between all strings contained in a std::vector.
 * @param args a vector of strings in which we have to insert whitespaces between them.
 * @return a string obtained by connecting all the strings in the vector with whitespaces.
 */
std::string spaceStr(const std::vector<std::string> &args)
{
    std::string res {};

    for (const std::string &str: args)
        res += str + " ";

    // Remove the trailing whitespace
    if (!res.empty())
        res.pop_back();

    return res;
}


/**
 * Function used to remove all trailing '\n' characters at the end of a string.
 * @param str the string in which we have to delete all the trailing '\n' characters.
 * @return a string without trailing '\n' characters.
 */
std::string deleteTrailingNewlines(std::string str)
{
    str.erase(std::remove(str.begin(), str.end(), '\n'), str.cend());
    return str;
}


/**
 * Function used to get the names of all the files contained in a specified directory.
 * @param inputDirPath a path to the directory from which to take the file names
 * @return a vector containing the name of all the files in the specified directory.
 */
std::vector<std::string> getAllFileNamesInDirectory(const std::string &inputDirPath)
{
    std::vector<std::string> res {};
    for (const auto &entry: getEntriesInAlphabeticalOrder(inputDirPath))
    {
        std::string fileName = getStringGivenPosAndToken(getWordAfterLastSymbol(entry.path(), '/'), '.', 0);
        res.push_back(fileName);
    }
    return res;
}


/**
 * Function used as a comparator to sort pairs of strings based on the length of the second element.
 */
static bool sortPairBySecondElementLength(const std::pair<std::string, std::string> &a, const std::pair<std::string, std::string> &b)
{
    // Sort in descending order of length.
    return a.second.length() > b.second.length();
}


/**
 * Function used as a comparator to sort a vector of strings in descending order based on the strings length.
 */
bool sortVectorByElementLength(const std::string &str1, const std::string &str2)
{
    // Sort in descending order of length.
    return str1.length() > str2.length();
}


/**
 * Function used to get the json representation of a file which name corresponds to the 'name' parameter.
 * @param inputDirPath the path to the directory where to get the file.
 * @param name the name of the file to get.
 * @return a json representation of the file named 'name' located in the directory specified by 'inputDirPath'.
 */
json getJsonFromFileName(const std::string &inputDirPath, const std::string &name)
{
    for (const auto &entry : getEntriesInAlphabeticalOrder(inputDirPath))
    {
        std::ifstream file(entry.path());
        std::string filename = getWordAfterLastSymbol(entry.path(), '/');

        // 2 accepted file formats: .tot and .xml
        if (filename.size() >= 4 && filename.compare(filename.size() - 4, 4, ".tot") == 0)
        {
            std::string fileNameWithoutExtension = getStringGivenPosAndToken(filename, '.', 0);
            if (name == fileNameWithoutExtension)
                return getJsonFromTOFile(file);
        }
        else if (filename.size() >= 5 and filename.compare(filename.size() - 5, 5, ".totj") == 0)
        {
            std::string fileNameWithoutExtension = getStringGivenPosAndToken(filename, '.', 0);
            if (name == fileNameWithoutExtension)
                return getJsonFromTOJFile(file);
        }
        else if (filename.size() >= 4 && filename.compare(filename.size() - 4, 4, ".xml") == 0)
        {
            std::string fileNameWithoutExtension = getStringGivenPosAndToken(filename, '.', 0);
            if (name == fileNameWithoutExtension)
                return getJsonFromFileStream(file);
        }
        else
        {
            std::cerr << "Error: file " << filename << " is not a .tot or .xml file" << std::endl;
        }
    }
}


#endif //UTOTPARSER_UTILS_H
