#include <iostream>
#include <fstream>
#include "nlohmann/json.hpp"

#include "utilities/StringsGetter.hpp"
#include "TAHeaders/TATileConstructor.hpp"
#include "utilities/Utils.hpp"
#include "utilities/CliHandler.hpp"
#include "TAHeaders/TADotConverter.hpp"

using json = nlohmann::json;


int main(int argc, char *argv[])
{
    try
    {
        CliHandler cliHandler(&argc, &argv);
        StringsGetter stringsGetter(cliHandler);

        std::vector<json> tiles;

        std::string nameTile = std::string();

        for (const auto &entry: getEntriesInAlphabeticalOrder(stringsGetter.getInputTilesDirPath()))
        {
            std::ifstream file(entry.path());

            if (static_cast<std::string>(entry.path()).find(".xml") == std::string::npos)
                continue;

            if (file.is_open())
            {
                // We obtain the json representation of a TA from the xml generated by UPPAAL.
                json j = getJsonFromFileStream(file);
                tiles.push_back(j);
            }
        }

        TATileConstructor taTileConstructor(tiles);
        json tiledTA = taTileConstructor.createTAFromTiles();

        std::cout << "\n\nResultingTiledTA:\n\n";
        std::cout << std::setw(4) << tiledTA << std::endl;

        if (cliHandler.isCmd(tdt))
        {
            std::string tiledTAName = "TiledTA";
            TADotConverter taDotConverter(stringsGetter.getOutputDOTsDirPath() + "/" += (tiledTAName + ".dot"));
            taDotConverter.translateTAtoDot(tiledTAName, tiledTA);
        }
    } catch (CommandNotProvidedException &e)
    {
        std::cerr << BHRED << e.what() << reset << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
